
#工作名字
name: glados-checkin
#
on:
  workflow_dispatch: 
  push:
  # 当对分支master进行push操作的时候，这个工作流就被触发了
    branches: [ master ]
  pull_request:
  #只运行特定分支master
    branches: [ master ]
  schedule:
  # 定时任务，在每天的24点 18点推送签到信息到邮箱
    - cron:  18 18 * * * 
jobs:

  checkin

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: Checkin
      run: |
        python3 ./main.py 

